# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import country_pb2 as country__pb2


class CountryInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCountry = channel.unary_unary(
                '/country.CountryInfo/GetCountry',
                request_serializer=country__pb2.PageRequest.SerializeToString,
                response_deserializer=country__pb2.CountryList.FromString,
                )


class CountryInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCountry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountryInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCountry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCountry,
                    request_deserializer=country__pb2.PageRequest.FromString,
                    response_serializer=country__pb2.CountryList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'country.CountryInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CountryInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCountry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/country.CountryInfo/GetCountry',
            country__pb2.PageRequest.SerializeToString,
            country__pb2.CountryList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
